# 46장 제너레이터와 async/await (3.28)
<hr>
<br>

## 1. 제너레이터란?
- ES6에서 도입된 `제너레이터`는 코드 블록의 실행을 일시 중지했다가 필요한 시점에 재개할 수 있는 특수한 함수다.
- `제너레이터 함수`는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다.
- `제너레이터 함수`는 함수 호출자와 함수의 상태를 주고받을 수 있다.
- `제너레이터 함수`를 호출하면 제너레이터 객체를 반환한다.
<br>
<br>

## 2. 제너레이터 함수의 정의
```jsx
// 제너레이터 함수 선언문
function genDecFunc(){
    yield 1;
}

// 제너레이터 함수 표형식
const getExpFunc = func* () {
    yield 1;
}

// 제너레이터 메서드
const obj = {
    * genObjMethod(){
        yield 1;
    };
};

// 제너레이터 클래스 메서드
class Myclass {
    * genClsMethod(){
        yield 1;
    }
}
```
```jsx
// 제너레이터 함수는 화살표 함수로 정의할 수 없다.
const genArrowFunc = * () => {
    yield 1;
};  // SyntaxError


// 제너레이터 함수는 new 연산자와 함께 생성자 함수로 호출할 수 없다.
function* genFunc(){
    yield 1;
}
new genFunc();  //TypeError
```
<br>

## 3. 제너레이터 객체
- 제너레이터 함수를 호출하면 함수 코드블록을 실행하는 것이 아니라 `제너레이터 객체`를 생성해 반환한다.
- 제너레이터 함수가 반환한 제너레이터 객체는 `이터러블`이면서 동시에 `이터레이터`다.

## 4. 제너레이터의 일시 중지와 재개
- `yield`키워드는 제너레이터 함수의 실행을 일시 중지 시키거나 뒤에 오는 표현식의 평가 결과를 제너레이터 함수 호출자에게 반환한다.
- 제너레이터는 함수 호출자에게 제어권을 양도하여 필요한 시점에 함수 실행을 재개할 수 있다.

## 5. 제너레이터의 활용
#### 5.1 이터러블의 구현
#### 5.2 비동기 처리
- 제너레이터 함수는 `next` 메서드와 `yield` 표현식을 통해 함수 호출자와 함수의 상태를 주고받을 수 있다.
- 프로미스의 후속 처리 메서드 `then/catch/finally` 없이 비동기 처리 결과를 반환하도록 구현할 수 있다.

## 6. async/await
- 비동기 처리를 동기 처리처럼 동작하도록 구현할 수 있는 `async/await`가 ES8에서 도입되었다.
#### 6.1 async 함수
- `async` 함수가 명시적으로 프로미스를 반환하지 않더라도 암묵적으로 반환값을 `resolve`하는 프로미스를 반환한다.
```jsx
// async 함수 선언문
async function foo(n){return n;}
foo(1).then(v=> console.log(v));    // 1

// async 함수 표현식
const bar = async function(n){return n;}
bar(2).then(v=> console.log(v));    // 2

// async 화살표 함수
const baz = async n => n;
baz(3).then(v=> console.log(v));    // 3

// async 메서드
const obj = {
    async foo(n){return n;}
};
obj.foo(4).then(v=> console.log(v));    // 4

// async 클래식 메서드
class MyClass{
    async bar(n){return n; }
}
const myClass = new myClass();
myClass.bar(5).then(v=> console.log(v));    // 5
```

#### 6.2 await 키워드
- `await` 키워드는 프로미스가 `settled`한 상태(비동기 처리가 수행된 상태)가 될 때까지 대기하다가 `settled` 상태가 되면 프로미스가 `resolve`한 처리 결과를 반환한다.
- **`await` 키워드는 반드시 프로미스 앞에서 사용해야 한다.**

#### 6.3 에러 처리
- 콜백 패턴의 단점 중 가장 심각한 것은 에러 처리가 곤란하다는 것이다.
- 에러는 콜 스택의 아래 방향으로 전파된다. 
```jsx
try {
    setTimeout(()=> {throw new Error('Error'); }, 1000);
} catch(e){
    // 에러를 캐치하지 못한다.
    console.error('캐치한 에러', e);
}

// async 함수 내에서 catch 문을 사용해서 에러 처리를 하지 않으면 async 함수는 발생한 에러를 reject하는 프로미스를 반환한다. 따라서 async 함수를 호출하고 Promise.prototype.catch 후속 처리 메서드를 사용해 에러를 캐치할 수도 있다.
const fetch = require('node-fetch');

const foo = async() =>{
    const wrongUrl = 'https://wrong/url';

    const response = await fetch(wrongUrl);
    const data = await response.json();
    return data;
};
foo()
    .then(console.log)
    .catch(console.error);      //TypeError
```